spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:25433/${DB_NAME:avengers}
    username: ${DB_USER:dio.avenger}
    password: ${DB_PASSWORD:dio.avenger}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true